name: "airbyte-ruby"

on:
  push:
    branches:
      - main
  pull_request:

env:
  CI: "true"
  TAG: "0.1.0"

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Linter
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - name: Rubocop linter
      run: bundle exec rubocop -P
  specs:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Rspec tests
      run: bundle exec rspec spec
    - name: Upload coverage data to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        directory: ./coverage/
        file: ./coverage/.resultset.json
  generate_release:
    name: Generate release
    needs: [lint, specs]
    if: "github.ref == 'refs/heads/main'"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        name: Create a GitHub release
        with:
          generateReleaseNotes: true
          tag: ${{ env.TAG }}
          name: ${{ env.TAG }}
          body: ${{ steps.tag_version.outputs.changelog }}
  rubygems:
    name: Push to RubyGems
    needs: [ lint, specs, generate_release ]
    if: "github.ref == 'refs/heads/main'"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Release Gem
        if: "github.ref == 'refs/heads/main'"
        uses: discourse/publish-rubygems-action@v2-beta
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
          RELEASE_COMMAND: rake release
          GIT_EMAIL: ci@quentinchampenois.com
          GIT_NAME: Airbyteruby